service: axie-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  profile: axie-admin
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Resource: "*"
          Action: "*"

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

package:
  individually: true

functions:
  create:
    handler: api/handler.create

    events:
      - http: GET /

  update:
    handler: api/handler.update

    events:
      - http: GET /
